name: Build
run-name: Build Ubuntu
on: push
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - run: mkdir build
      - run: cd build
      - run: cmake .. -GNinja
      - run: ninja